name: Deploy

on:
  push:
    branches:
      - master

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "the-name-of-the-game"
          heroku_email: "tgclayton1@gmail.com"

